# Copyright (c) 2010-2025 Evolveum and contributors
#
# Licensed under the EUPL-1.2 or later.

version: "3.9"

services:
  smart-integration-ms:
    build: .
    ports:
      - "${HOST_PORT:-8090}:${CONTAINER_PORT:-8090}"
    environment:
      LOGGING__LEVEL: info
